version: '3.7'
services:
  app:
    container_name: "app"
    image: app
    environment:
      - MONGO_URL=mongodb://mongo_db/test_database
      - JWT_SECRET='mytoken'
      - ALGORITM='HS256'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db

  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./conf.d/app.conf
    networks:
      - custom


  mongo_db:
    image: mongo:latest
    container_name: "mongo_db"
    ports:
      - "27015:27015"
    networks:
      - custom

networks:
  custom:
    driver: bridge